### PR TITLE
Windows driver compliance update: Move NFC sample driver to run from driver store

### PR DESCRIPTION
**Pull request by tenglu83**
Move NFC sample driver to run from driver store

### CODE REVIEW

**Comment by jasonknichel** [comment]
@tenglu83 - I see that your INF change updated ServiceBinary directive in its service install section for WudfRd to be DIRID 13.  However, this INF file does not payload WudfRd.sys so the file %13%\wudfrd.sys would not exist.  To fix the WudfRd reference, you should update the INF to do an Include/Needs of wudfrd.inf to pull in the WudfRd service.  See the comments in %windir%\inf\wudfrd.inf on how to Include/Needs it properly.  You can also see infverif asking to update to Include/Needs of WudfRd with this error from 'infverif /v /w':

ERROR(2086) in S:\git\testDrv\nfc\NfcCxSample\windows-drivertemplate-nfc\windows-drivertemplate-nfc.inf, line 33: Replaced legacy pattern in section 'WUDFRD_ServiceInstall' using 'wudfrd_include_needs' to follow best practices.

**Comment by jasonknichel** [comment]
@tenglu83 - The PR shows that this branch has conflicts with the develop branch.  Can you please resolve those conflicts?

**Comment by jasonknichel** [comment]
@tenglu83 - Viewing the INF diffs, it looks like you changed %12%/12 to %13%/13.  That results in your DestinationDirs and other file references to make it look like the file is in %13%\umdf\windows-drivertemplate-nfc.dll but the [SourceDisksFiles] directive was not updated so the file is really %13%\windows-drivertemplate-nfc.dll.  Can you please update the references in DestinationDirs and other file references to treat the file as in the root of the driver package (%13%\windows-drivertemplate-nfc.dll)?  You can see this problem in the inf with 'infverif /v /w':
ERROR(1100) in nfc\NfcCxSample\windows-drivertemplate-nfc\windows-drivertemplate-nfc.inf, line 61: Source and destination directory must match for file 'windows-drivertemplate-nfc.dll' when using CopyFiles with DIRID 13.

**Review by jasonknichel — CHANGES_REQUESTED** [review]
Please see my other comments.

**Comment by tenglu83** [comment]
> @tenglu83 - I see that your INF change updated ServiceBinary directive in its service install section for WudfRd to be DIRID 13. However, this INF file does not payload WudfRd.sys so the file %13%\wudfrd.sys would not exist. To fix the WudfRd reference, you should update the INF to do an Include/Needs of wudfrd.inf to pull in the WudfRd service. See the comments in %windir%\inf\wudfrd.inf on how to Include/Needs it properly. You can also see infverif asking to update to Include/Needs of WudfRd with this error from 'infverif /v /w':
> 
> ERROR(2086) in nfc\NfcCxSample\windows-drivertemplate-nfc\windows-drivertemplate-nfc.inf, line 33: Replaced legacy pattern in section 'WUDFRD_ServiceInstall' using 'wudfrd_include_needs' to follow best practices.

Fixed.

**Comment by tenglu83** [comment]
> @tenglu83 - Viewing the INF diffs, it looks like you changed %12%/12 to %13%/13. That results in your DestinationDirs and other file references to make it look like the file is in %13%\umdf\windows-drivertemplate-nfc.dll but the [SourceDisksFiles] directive was not updated so the file is really %13%\windows-drivertemplate-nfc.dll. Can you please update the references in DestinationDirs and other file references to treat the file as in the root of the driver package (%13%\windows-drivertemplate-nfc.dll)? You can see this problem in the inf with 'infverif /v /w': ERROR(1100) in nfc\NfcCxSample\windows-drivertemplate-nfc\windows-drivertemplate-nfc.inf, line 61: Source and destination directory must match for file 'windows-drivertemplate-nfc.dll' when using CopyFiles with DIRID 13.

Fixed.

**Comment by jasonknichel** [comment]
@tenglu83 - it looks like your commit to merge in the develop branch somehow deleted the contents of the INF file you are trying to modify
image

**Comment by jasonknichel** [comment]
RE: my comments about Include/Needs of wudfrd.inf

Unfortunately, that was not fixed correctly in your commit that tried to address that.  You added new [DDInstall] sections that did the Include/Needs of wudfrd.inf instead of adding the Include/Needs to your existing MyDevice_Install.NT* sections.

RE: references to file paths that were updated to DIRID 13

In your commit that tried to address my comments, I still see %13%\UMDF\windows-drivertemplate-nfc.dll instead of %13%\windows-drivertemplate-nfc.dll

**Comment by tenglu83** [comment]
@jasonknichel For some reason this PR is corrupted. Please review the new one:
https://github.com/microsoft/Windows-driver-samples/pull/851

**Comment by jasonknichel** [comment]
This has been replaced by https://github.com/microsoft/Windows-driver-samples/pull/851 .  Closing this PR.

**Pull request closed without merging**
