### PR TITLE
Disabled warning 4595 to avoid errors in the SDK header files.

### PR DESCRIPTION
**Pull request by girishp**

### CODE REVIEW

**Comment by redwhale13** [comment]
Please dont diss able im have so much grief trying to figure this stuff out
my email address is for 1309 Joe at gmail.com and buccij 203 at gmail.com
end back jrb 13 at gmail.com these are my address is and I can't figure out
how to keep them all on

**Comment by wm1** [comment]
Suppressed by pull request #114 Resolve SAL warnings and suppress 4595

**Comment by girishp** [comment]
We want to suppress in the sample driver here. But an alternative approach
is there in the history. Look for _NEW_DELETE_OPERATORS flag.

**Comment by girishpattabiraman** [comment]
Please see change subset:
[https://github.com/Microsoft/Windows-driver-samples/pull/114/commits/42cd81689c12568ae4451fe956da6bb5e453e058](url)

**Comment by girishpattabiraman** [comment]
The warning 4595 is about using the "new" and "delete" operators defined in the "stdunk.h" header. The MSDN recommendation is to define the compiler flag "_NEW_DELETE_OPERATORS_ to suppress the operator overloads in "stdunk.h" and then to define the operator overloads locally in your driver. We're suppressing the warning for now in the sample driver before coming up with an easier solution than defining locally in every driver.

**Pull request closed without merging**
