### PR TITLE
Add ARM64 as target platform on multiple samples

### PR DESCRIPTION
**Pull request by NeoAdonis**
### Why is this change being made?

* *Commitment to ARM64 Compatibility*: By expanding our support to ARM64, we demonstrate our commitment to staying current and providing comprehensive resources for developers.
* *Ecosystem Alignment*: Supporting ARM64 aligns with broader industry trends and ensures that our samples remain relevant and useful to a wider audience.

### What changed?
We've made several significant changes to achieve better ARM64 compatibility across the repository:

* **Automated Debug and Release Configurations**: Leveraging a script, we automatically added Debug and Release configurations for ARM64 to all Visual Studio solutions and platforms.
* **Expanded ARM64 Coverage**: Previously, only a handful of solutions (19 out of 130) supported ARM64. Now, 107 additional solutions have been updated to include ARM64 configurations, so now 126 out of 130 support ARM64. The remaining projects will be handled separately
* **Specific Modifications**: These were done using the same script to ensure consistency:
   - Removed the `BufferSecurityCheck` from ARM64 configurations when no `EntryPoint` is defined (affects 1 sample).
   - Eliminated the `/CETCOMPAT` linker option from ARM64 configurations (affects 1 sample).
   - Adjusted ARM64-specific paths to ensure successful compilation.
   - Set the minimum NDIS version to 6.30 for ARM64 compatibility (affects most network samples).
   - Added ARM64 configuration settings to relevant INF files (affects 2 samples).

### **How was the change tested?**
We validated these updates by building all samples targeting ARM64.

**Before**:

Status | Samples on ARM64 (Debug/Release)
-- | --
Succeeded | 19
Unsupported | 109
Excluded | 2

**After**:

Status | Samples on ARM64 (Debug/Release)
-- | --
Succeeded | 126
Unsupported | 3
Excluded | 1

No changes for x64 samples (128 succeeded, 2 excluded for both Debug and Release)

### CODE REVIEW

**Comment by JakobL-MSFT** [comment]
@NeoAdonis.  This PR looks amazing.  

Please continue to write down every action you needed to take as you port majority of our samples to support arm64.

So far:
* 
* Run your script.
* Edit 2 inf files 

Let's put together statistics:
* Using in market EWDK.ni_release_svc_prod1.22621.2428
* Samples: 131
* Configuration: 2
* Platforms: 2

Before your changes:
```
For (  x64,Debug)   : Succeeded: 126, Excluded: 5, Unsupported:   0; Failed: 0.
For (arm64,Debug)   : Succeeded:  18, Excluded: 4, Unsupported: 109, Failed: 0.
For (arm64,Release) : Succeeded:  18, Excluded: 4, Unsupported: 109, Failed: 0.
```

Running your script (and not fixing any build errors):
```
For (  x64,Debug)   : (Unchanged)
For (  x64,Release)   : (Unchanged)
For (arm64,Debug)   : ???
For (arm64,Release) : ???
```

Fixing inf errors:
```
For (  x64,Debug)   : (Unchanged?)
For (  x64,Release)   : (Unchanged?)
For (arm64,Debug)   : ???
For (arm64,Release) : ???
```

Fixing old kmdf to new kmdf:
```
For (  x64,Debug)   : (Unchanged?)
For (  x64,Release)   : (Unchanged?)
For (arm64,Debug)   : ???
For (arm64,Release) : ???
```

Now what?

**Comment by JakobL-MSFT** [comment]
Looks great. I'd still like to understand the statistics (see above).

**Review by idigdoug — APPROVED** [review]

**Review by JakobL-MSFT — APPROVED** [review]
Fantastic.  Please check for regressions with "in market" EWDK (should be handled by GitHub CI).  Please check for regression with GE EWDK.  Please provide the statistics discussed above.

**Review by cgallred — APPROVED** [review]

**Comment by NeoAdonis** [comment]
@JakobL-MSFT I have added stats to the PR description. As for the next step, there are 4 samples that need fixes before adding support for arm64 to them. These cases will be handled on separate pull requests.

**Comment by JakobL-MSFT** [comment]
> @JakobL-MSFT I have added stats to the PR description. As for the next step, there are 4 samples that need fixes before adding support for arm64 to them. These cases will be handled on separate pull requests.

Great. Thank you for providing all these details!!!

FYI: @GelataioMatto

**Review by JakobL-MSFT — APPROVED** [review]

**Pull request merged**
