### PR TITLE
devcon: Made DumpDeviceDriversCallback be __stdcall.

### PR DESCRIPTION
**Pull request by DavidEGrayson**
I've noticed the recent activity in this repository and was wondering if you would accept some pull requests for better MinGW support.  Here is the first one.  My commit message explains it pretty well.  Thanks!

### CODE REVIEW

**Comment by DavidEGrayson** [comment]
I also have several changes I'd like to make for usbview, but I'll wait to hear back from you before putting effort into making another pull request.

**Comment by wm1** [comment]
Would it be better to use CALLBACK directly?

**Comment by DavidEGrayson** [comment]
Yes, I think so, actually.  Thanks for the response; I'll update the pull request some time.

**Comment by DavidEGrayson** [comment]
I changed the pull request and tested that I can still build devcon with MinGW.  I have not tested Visual Studio.

**Comment by DavidEGrayson** [comment]
Thanks!

**Pull request merged**
