### PR TITLE
replace deprecated exallocatepool* APIs with their modern replacement

### PR DESCRIPTION
**Pull request by Spruill-1**
Re-doing this PR against the develop branch.

### CODE REVIEW

**Comment by Spruill-1** [comment]
@JakobL-MSFT Correct target branch this round?

**Comment by JakobL-MSFT** [comment]
Yes, right branch :-)  Thank you so much.   I have an unrelated comment I will post separately.

**Review by JakobL-MSFT — CHANGES_REQUESTED** [review]
Hi David.  Let us please handle internal bug 48004707 prior to completing PR 1088.  I sent email.

**Review by JakobL-MSFT — APPROVED** [review]

**Comment by osy** [comment]
@JakobL-MSFT This change is broken. You cannot replace `ExAllocatePoolWithTag` with `ExAllocatePool2` directly because the argument type changed from `POOL_TYPE` to `POOL_FLAGS`. The driver will refuse to load with Code 31 (STATUS_NO_MEMORY). May I ask how this change was tested by Microsoft before being merged?

**Pull request merged**
