### PR TITLE
replacing mft0 with dmft

### PR DESCRIPTION
**Pull request by jiteshkris**

### CODE REVIEW

**Comment by jiteshkris** [comment]
@kasumman is added to the review. #Closed

**Comment by jiteshkris** [comment]
@NaveenThum is added to the review. #Closed

**Comment by jiteshkris** [comment]
@j-leungyy is added to the review. #Closed

**Comment by jiteshkris** [comment]
@SangChoe is added to the review. #Closed

**Comment by jiteshkris** [comment]
@gerritsMSFT is added to the review. #Closed

**Comment by jiteshkris** [comment]
@LPBourret is added to the review. #Closed

**Comment by NaveenThum** [comment]
@jiteshkris , is this code now in sync with what we have in OS repo?

**Pull request merged**
